services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend:/backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/frontend