services:
  backend:
    environment:
      FRONTEND_URL: "https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
      BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/backend
    command: air

  frontend:
    environment:
      BACKEND_URL: "https://${CODESPACE_NAME}-4567.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend